export const HARMONY_COMMON_LINKS = {
  appStatus: 'https://harmony.betteruptime.com',
  cookiePolicy: 'https://docs.harmony.one/home',
  crossChainDocs: 'https://docs.harmony.one/home',
  discord: 'https://discord.com/invite/fzB9MGz5',
  docs: 'https://docs.harmony.one/home',
  faqFeesDocs: 'https://docs.harmony.one/home',
  faqGasFeesDocs: `https://docs.harmony.one/home`,
  hacken: 'https://coinmarketcap.com/currencies/harmony/',
  lpDocs: 'https://docs.harmony.one/home',
  maintenanceWindowDocs: 'https://docs.harmony.one/home',
  marketingSite: 'https://coinmarketcap.com/currencies/harmony/',
  openTicketDiscord:
    'https://discord.com/channels/944256846628266024/944256847387426925/945368373322186792',
  privacyPolicy: 'https://harmonyexchange.com/docs/PrivacyPolicy.pdf',
  productSpecDocs: 'https://docs.harmony.one/home',
  referralDocs: 'https://docs.harmony.one/home',
  spotTradingLearnMore: 'https://docs.harmony.one/home',
  spreadDocs: 'https://docs.harmony.one/home',
  stats: 'https://stats.harmonyexchange.com',
  termsOfUse: 'https://docs.harmony.one/home',
  tpslDocs: 'https://docs.harmony.one/home',
  tutorials: 'https://docs.harmony.one/home',
  twitter: 'https://twitter.com/harmonyprotocol',
  wrapEth: 'https://docs.harmony.one/home',
};
